services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'postgres-db'
      POSTGRES_USER: 'owner'
      POSTGRES_PASSWORD: 'owner'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  ibmmq:
    image: 'ibmcom/mq'
    ports:
      - '1414:1414'
      - '9443:9443'
    environment:
      LICENSE: 'accept'
      MQ_QMGR_NAME: 'QM1'

